In [4]:
import pandas as pd
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

In [7]:
heart_data=pd.read_csv('/content/heart_disease_data.csv')
heart_data.head()

   age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1        0      150      0      2.3      0   0     1       1
1   37    1   2       130   250    0        1      187      0      3.5      0   0     2       1
2   41    0   1       130   204    0        0      172      0      1.4      2   0     2       1
3   56    1   1       120   236    0        1      178      0      0.8      2   0     2       1
4   57    0   0       120   354    0        1      163      1      0.6      2   0     2       1

In [8]:
heart_data.shape

(303, 14)

In [9]:
heart_data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

# MODEL SELECTION

In [10]:
X=heart_data.drop(columns='target',axis=1)
Y=heart_data['target']

creating the list of models

In [12]:
models_list=[LogisticRegression(max_iter=1000),SVC(kernel='linear'),KNeighborsClassifier(),RandomForestClassifier(random_state=0)]

- Comparing the models with default hyperparameter values using Cross Validation
- model selection based on cross validation

In [15]:
def compare_models_cross_val():

  for model in models_list:
    cross_scores=cross_val_score(model,X,Y,cv=5)
    avg_cross_score=sum(cross_scores)/len(cross_scores)
    avg_cross_score=avg_cross_score*100
    avg_cross_score=round(avg_cross_score,2)

    print('for',model,'model the accuracy is:',avg_cross_score,'%')
    print('---------------------------------------------------------------')

In [16]:
compare_models_cross_val()

for LogisticRegression(max_iter=1000) model the accuracy is: 82.83 %
---------------------------------------------------------------
for SVC(kernel='linear') model the accuracy is: 82.83 %
---------------------------------------------------------------
for KNeighborsClassifier() model the accuracy is: 64.39 %
---------------------------------------------------------------
for RandomForestClassifier(random_state=0) model the accuracy is: 83.81 %
---------------------------------------------------------------

Comparing the models with different Hyperparameter values using **GridSearchCV**

In [17]:
models_list=[LogisticRegression(max_iter=10000),SVC(),KNeighborsClassifier(),RandomForestClassifier(random_state=0)]

In [18]:
#parameters Hyperparameters list
Hyparameters_Lists={
    'LogisticRegression':{
        'C':[1,5,10,20]
    },
    'SVC_parameters':{
        'C':[1,5,10,20],
        'kernel' : ['linear','poly','rbf','sigmoid'],
    },
    'KNN_hyperparameters' : {

        'n_neighbors' : [3,5,10]
    },


    'random_forest_hyperparameters' : {

        'n_estimators' : [10, 20, 50, 100]
    }
}

In [27]:

model_keys = list(Hyparameters_Lists.keys())
print(Hyparameters_Lists['LogisticRegression'])

{'C': [1, 5, 10, 20]}

In [33]:
def campare_cross_Hyper_parameters(List_of_Models,List_of_hyper_parameters):
  i=0
  result=[]
  for model in List_of_Models:

    key=model_keys[i]
    params=List_of_hyper_parameters[key]

    print(model)
    print(params)
    i+=1
    classifer=GridSearchCV(model,params,cv=5)
    classifer.fit(X,Y)

    result.append({
        'model_name':model,
        'parames':classifer.best_params_,
        'highst_score':classifer.best_score_
    })


  Results=pd.DataFrame(result, columns = ['model_name','parames','highst_score'])
  return Results

In [34]:
campare_cross_Hyper_parameters(models_list,Hyparameters_Lists)

LogisticRegression(max_iter=10000)
{'C': [1, 5, 10, 20]}
SVC()
{'C': [1, 5, 10, 20], 'kernel': ['linear', 'poly', 'rbf', 'sigmoid']}
KNeighborsClassifier()
{'n_neighbors': [3, 5, 10]}
RandomForestClassifier(random_state=0)
{'n_estimators': [10, 20, 50, 100]}

                               model_name                       parames  highst_score
0      LogisticRegression(max_iter=10000)                      {'C': 5}      0.831585
1                                   SVC()  {'C': 1, 'kernel': 'linear'}      0.828306
2                  KNeighborsClassifier()            {'n_neighbors': 5}      0.643880
3  RandomForestClassifier(random_state=0)         {'n_estimators': 100}      0.838087